services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=postgres://plantcare:password@db:5432/plantcare
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: plantcare
      POSTGRES_PASSWORD: password
      POSTGRES_DB: plantcare
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - plantcare-network

volumes:
  pgdata:

networks:
  plantcare-network:
    driver: bridge