# Generated by Django 5.1.7 on 2025-03-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=255,
                     unique=True,
                     verbose_name='Nom')),
                ('variety',
                 models.CharField(
                     blank=True,
                     max_length=255,
                     null=True,
                     verbose_name='Variété')),
                ('plant_type',
                 models.CharField(
                     choices=[
                         ('indoor',
                          'Plante d’intérieur'),
                         ('outdoor',
                          'Plante d’extérieur'),
                         ('succulent',
                          'Succulente'),
                         ('flower',
                          'Fleur'),
                         ('tree',
                          'Arbre')],
                     max_length=20,
                     verbose_name='Type de plante')),
                ('purchase_date',
                 models.DateField(
                     blank=True,
                     null=True,
                     verbose_name='Date d’achat')),
                ('location',
                 models.CharField(
                     blank=True,
                     max_length=255,
                     null=True,
                     verbose_name='Emplacement')),
                ('description',
                 models.TextField(
                     blank=True,
                     null=True,
                     verbose_name='Description')),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True,
                     verbose_name='Date d’ajout')),
            ],
            options={
                'verbose_name': 'Plante',
                'verbose_name_plural': 'Plantes',
                'ordering': ['-created_at'],
            },
        ),
    ]
