# Generated by Django 5.1.7 on 2025-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='fertilizing_frequency',
            field=models.IntegerField(default=30, verbose_name='Fréquence de fertilisation (jours)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_fertilizing',
            field=models.DateField(blank=True, null=True, verbose_name='Dernière fertilisation'),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_pruning',
            field=models.DateField(blank=True, null=True, verbose_name='Dernière taille'),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_repotting',
            field=models.DateField(blank=True, null=True, verbose_name='Dernier rempotage'),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_watering',
            field=models.DateField(blank=True, null=True, verbose_name='Dernier arrosage'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pruning_frequency',
            field=models.IntegerField(default=90, verbose_name='Fréquence de taille (jours)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='repotting_frequency',
            field=models.IntegerField(default=365, verbose_name='Fréquence de rempotage (jours)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering_frequency',
            field=models.IntegerField(default=7, verbose_name='Fréquence d’arrosage (jours)'),
        ),
    ]
