# Generated by Django 5.1.7 on 2025-03-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Objet',
                'verbose_name_plural': 'Objets'},
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                max_length=255,
                unique=True,
                verbose_name='Nom'),
        ),
    ]
