# Generated by Django 5.1.7 on 2025-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'api',
            '0002_plant_fertilizing_frequency_plant_last_fertilizing_and_more'
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='humidity_level',
            field=models.CharField(
                choices=[
                    ('low',
                     'Sec'),
                    ('medium',
                     'Moyen'),
                    ('high',
                     'Humide')],
                default='medium',
                max_length=10,
                verbose_name='Humidité'),
        ),
        migrations.AddField(
            model_name='plant',
            name='sunlight_level',
            field=models.CharField(
                choices=[
                    ('low',
                     'Faible'),
                    ('medium',
                     'Moyen'),
                    ('high',
                     'Élevé')],
                default='medium',
                max_length=10,
                verbose_name='Ensoleillement'),
        ),
        migrations.AddField(
            model_name='plant',
            name='temperature',
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name='Température (°C)'),
        ),
    ]
