# Generated by Django 5.1.7 on 2025-03-17 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plant_humidity_level_plant_sunlight_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plant_photos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Légende')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléversement')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.plant')),
            ],
            options={
                'verbose_name': 'Photo de Plante',
                'verbose_name_plural': 'Photos de Plantes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
