name: Django CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:14
                env:
                    POSTGRES_USER: user
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: test_db
                ports:
                    - 5432:5432
                options: --health-cmd "pg_isready -U user -d test_db" --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - name: Checkout du code
              uses: actions/checkout@v4

            - name: Configurer Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'

            - name: Installer les dépendances
              run: |
                  python -m venv env
                  source env/bin/activate
                  pip install -r requirements.txt

            - name: Vérifier la syntaxe avec flake8
              run: |
                  source env/bin/activate
                  pip install flake8
                  flake8 .

            - name: Exécuter les tests Django
              env:
                  DATABASE_URL: postgres://user:password@localhost:5432/test_db
              run: |
                  source env/bin/activate
                  python manage.py test
